In [1]:
import numpy as np

In [2]:
# Create a Numpy Array

arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
# Difference between Python list and Numpy arry

list1 = [1,2,3]
arr = np.array([1,2,3])

print(list1 * 2)                   # in lists *2 repeats values
print(arr * 2)                     # array * 2 multiplies each elements

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [4]:
# Types of NumPy Arrays

# 1D Array

arr = np.array([1,2,3,4])
print(arr)

# 2D Array

arr = np.array([
    [1,2,3],
    [4,5,6]
    ])

print(arr)

# 3D Array

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Array Properties

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr.ndim)  # number of dimensions
print(arr.shape) # rows and columns
print(arr.size)  # total elements
print(arr.dtype)  # data type

2
(2, 3)
6
int64


In [6]:
# Creating Special Arrays
# Array of Zeroes

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [7]:
# 2D Zeroes
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Array of one
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Array with same value
arr = np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [10]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 6. arrange and linespace

# np.arrange()

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# np.linespace()--> It creates 5 equally spaced values between 1 and 10.
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [13]:
# Indexing and Slicing

# 1D indexing 
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [14]:
# 1D Slicing 
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[50 40 30 20 10]


In [15]:
# 2D Indexing ans Slicing

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,0])
print(arr[1,2])
print(arr[2,1])
print(arr[1])    # Access full row
print(arr[:, 1]) # Access full column
print(arr[0:2, 1:3]) # Slice rows and columns

10
60
80
[40 50 60]
[20 50 80]
[[20 30]
 [50 60]]


In [16]:
# Mathematical Expressions

arr = np.array([10,20,30,40])
print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 2)

[15 25 35 45]
[ 5 15 25 35]
[ 50 100 150 200]
[ 5. 10. 15. 20.]


In [17]:
# Operations between arrays
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


In [18]:
# Useful Mathematical Functions

arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))
print(np.log(arr))

[1. 2. 3. 4.]
[  1  16  81 256]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]


In [19]:
#Trignometric Functions
arr = np.array([0,30,45,60,90])
radians = np.deg2rad(arr)
print(np.sin(radians))
print(np.cos(radians))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [20]:
# Aggregate Functions

arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


150
30.0
30.0
10
50
14.142135623730951
200.0


In [23]:
# Axis in NumPy
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(np.sum(arr))

# Column-wise sum
print(np.sum(arr, axis=0))

# Row-wise sum
print(np.sum(arr, axis=1))

210
[50 70 90]
[ 60 150]


In [29]:
# Reshape Array
arr = np.arange(1,13)
print(arr)

print("####################")

# Convert 1D to 2D Array

new_arr = arr.reshape(3,4)
print(new_arr)

print("####################")

# Convert to 4 rows and 3 columns

new_arr2 = arr.reshape(4,3)
print(new_arr)

"""
Important: total elements must match.

12 elements = 3 * 4
12 elements = 4 * 3
"""

[ 1  2  3  4  5  6  7  8  9 10 11 12]
####################
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
####################
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# Flatten Array

arr = np.array([
    [1,2,3],
    [4,5,6]
])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [31]:
# Transpose

arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.T)        # Rows become columns and columns become rows.

[[1 4]
 [2 5]
 [3 6]]


In [34]:
# 16. Filtering Arrays

arr = np.array([10,25,30,45,50])

# Find values greater than 30
print(arr>30)

# Get Values Greater than 30
print(arr[arr>30])

# Multiple conditions

print(arr[(arr>20) & (arr<50)])      # &,|

[False False False  True  True]
[45 50]
[25 30 45]


In [37]:
# 17. np.where()

arr = np.array([45,75,32,90,60])

# Find indexes where condition is true

print(np.where(arr > 60))

# Replace values using condition

result = np.where(arr >=60,"Pass", "Fail")
print(result)

# np.where(condition, value_if_true, value_if_false)

(array([1, 3]),)
['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


In [39]:
# 18. Sorting

arr = np.array([40,10,30,20])
print(np.sort(arr))

[10 20 30 40]


In [40]:
# For 2D Array

arr = np.array([
    [3,2,1],
    [6,5,4]
])
print(np.sort(arr, axis=1))

[[1 2 3]
 [4 5 6]]


In [42]:
# 19. Unique Values

arr = np.array([1,2,3,2,4,4,2,3,5])
print(np.unique(arr))

# with counts

values,counts = np.unique(arr,return_counts=True)
print(values)
print(counts)

[1 2 3 4 5]
[1 2 3 4 5]
[1 3 2 2 1]


In [48]:
# 20. Stacking Arrays

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))     # Vertical Stack
print(np.hstack((a,b)))     # Horizontal Stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [49]:
# 21. Splitting Arrays

arr = np.array([1,2,3,4,5,6])
result = np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [55]:
# Random Arrays

# Random numbers between 0 and 1

arr = np.random.rand(5)
print(arr)

# Random Integers

arr = np.random.randint(1,100,5)
print(arr)

# 2D random integers

arr = np.random.randint(1,50, (3,4))
print(arr)

# Set Seed

np.random.seed(10) --> # Seed is used to get the same random values every time.

arr = np.random.randint(1,100,5)
print(arr)

[0.58332174 0.02517173 0.70920801 0.26556613 0.26360285]
[37 17 12 55 89]
[[44 34  9 37]
 [15 14  6 14]
 [26 14 29 23]]
[10 16 65 29 90]


In [58]:
# Matrix Operations

a = np.array([
    [1,2],
    [3,4]
])
b = np.array([
    [5,6],
    [7,8]
])

# Elementwise Multiplication

print(a*b)

# Matrix Multiplication

print(np.dot(a,b))
print(a @ b)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [61]:
# Linear Algebra

arr = np.array([
    [1,2],
    [3,4]
])

# Determinant

print(np.linalg.det(arr))

# Inverse Matrix

print(np.linalg.inv(arr))

# Eigenvalues and eigenvectors

values,vectors = np.linalg.eig(arr)
print(values)
print(vectors)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [63]:
# Broadcasting
"""
Broadcasting means NumPy automatically expands smaller arrays during operations.
"""

arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr + 5)

# Example 2:

arr = np.array([
    [10,20,30],
    [40,50,60]
])

b = np.array([1,2,3])

print(arr + b)    # Here b is addded to every row

[[15 25 35]
 [45 55 65]]
[[11 22 33]
 [41 52 63]]


In [68]:
# Advanced Indexing

arr = np.array([10,20,30,40,50])

# Selsect using index list

print(arr[[0,2,4]])

"""
Here, the list takes upto the value from 0 to 4 and it is taking a step 
of 2 everytime it moves forward.
"""

# For 2D

arr = np.array([
    [10,20],
    [30,40],
    [50,60]
])

"""
Here, the indexing is happening on the basis of row-wise 
basis whichever row number we write at starting point it marks 
as the begining of the array and the last value marks as the end
"""

print(arr[[0,2]])

[10 30 50]
[[10 20]
 [50 60]]


In [71]:
# 27. Copy vs View **

# View

arr = np.array([1,2,3,4])
view_arr = arr.view()
view_arr[0] = 100


print(arr)
print(view_arr)     # Changing view changes original array.

"""
in this view case we are viewing it using outplace method but the view
is applied on the original array so the changes gets reflected on that 
only.
"""

# Copy

arr = np.array([1,2,3,4])
copy_arr = arr.copy()
copy_arr[0] = 100

print(arr)
print(copy_arr)   # Changing copy doesn't affect the original array

[100   2   3   4]
[100   2   3   4]
[1 2 3 4]
[100   2   3   4]


In [75]:
# Handling Missing values
arr = np.array([10,20,np.nan,40,50])

# Check missing values

print(np.isnan(arr))

# ignore missing values while calculating mean

print(np.nanmean(arr))

# Replace missing values

arr = np.nan_to_num(arr,nan=0)
print(arr)

[False False  True False False]
30.0
[10. 20.  0. 40. 50.]


In [76]:
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)
iqr = q3 - q1

print(q1)
print(q3)
print(iqr)

10.0
40.0
30.0


In [79]:
# 30. Mini Practice Example

import numpy as np

marks = np.array([45,67,89,32,76,90,55])

print(f"Marks: {marks}")
print(f"Average: {np.mean(marks)}")
print(f"Highest: {np.max(marks)}")
print(f"Lowest: {np.min(marks)}")
print(f"Passed_Students: {marks >= 40}")
print(f"Failed_Students: {marks < 40}")

result = np.where(marks >= 40, "Pass","Fail")
print(result)

Marks: [45 67 89 32 76 90 55]
Average: 64.85714285714286
Highest: 90
Lowest: 32
Passed_Students: [ True  True  True False  True  True  True]
Failed_Students: [False False False  True False False False]
['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass']
