# Basic

In [2]:
import numpy as np

In [10]:
# Q1. Create an array from 1 to 10

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# Q2. Create an 3X3 matrix of zeroes

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Q3. Create an array of even numbers from 2 to 20.

arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [13]:
# Q4. Find shape,size and dimensions of a 2D array.

arr_2d = np.array([
    [1,2],
    [4,5]
])


print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Dimension:", arr_2d.ndim)

Shape: (2, 2)
Size: 4
Dimension: 2


In [12]:
arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


# Intermediate

In [16]:
# Q6. Create a 3 X 4 array and reshape it into 4 X 3.

arr = np.arange(1,13).reshape(3,4)
print(f"Original 3 X 4 array:")
print(arr)

reshaped_array = arr.reshape(4,3)
print(reshaped_array)

Original 3 X 4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
# Q7. Find row-wise and column-wise sum.

arr = np.array([
    [1,2],
    [5,8]
])
print(np.sum(arr))
print(f"The row-wise sum is: {np.sum(arr, axis=1)}")
print(f"The Column-wise sum is: {np.sum(arr,axis=0)}")

16
The row-wise sum is: [ 3 13]
The Column-wise sum is: [ 6 10]


In [27]:
# Q8. Filter. all values greater than 50.

arr = np.array([45,67,89,32,76,90,55])

print(arr[arr > 50])

[67 89 76 90 55]


In [28]:
# Q9. Replace values less than 40 with 0

arr = np.array([10, 25, 40, 55, 30, 70])

arr[arr < 40] = 0
print(arr)

[ 0  0 40 55  0 70]


In [25]:
# Q10. FIND UNIQUE VALUES AND THEIR COUNTS

arr = np.array([1,2,3,2,4,4,2,3,5])
print(np.unique(arr))

value,counts = np.unique(arr,return_counts=True)
print(f"The Value is: {value}, The Count is: {counts}")

[1 2 3 4 5]
The Value is: [1 2 3 4 5], The Count is: [1 3 2 2 1]


# Advanced

In [35]:
# Q11. Perform matrix multiplication of two 2 X 2 matrices.

arr1 = np.arange(1,5).reshape(2,2) 
arr2 = np.arange(9,13).reshape(2,2)
print(arr1)
print(arr2)

result = arr1 @ arr2
multiply = np.matmul(arr1,arr2)
mat_mul = np.dot(arr1,arr2)
print(result)
print(multiply)
print(mat_mul)

[[1 2]
 [3 4]]
[[ 9 10]
 [11 12]]
[[31 34]
 [71 78]]
[[31 34]
 [71 78]]
[[31 34]
 [71 78]]


In [37]:
# Q12. Find Determinant and inverse of a matrix

arr = np.array([
    [1,2],
    [3,4]
])

# Determinant

print(f"Determinant: {np.linalg.det(arr)}")

# Inverse

print(f"Inverse: {np.linalg.inv(arr)}")

Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
# Q13. Generate random marks of 10 students and classify Pass/Fail

marks = np.random.randint(0,101,10)

result = np.where(marks >= 40 ,"Pass","Fail")
print("Marks:", marks)
print("Result:", result)

Marks: [ 3 96 26 16  9  8 84 49 76 88]
Result: ['Fail' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']


In [41]:
# Q14. Find Q1,Q3 and IQR of an array

arr = np.array([10,20,30,40,50,60,70,80])
q1 = np.percentile(arr,25)
q3 = np.percentile(arr,75)
iqr = q3 - q1

print("Q1:",q1)
print("Q3:",q3)
print("IQR:",iqr)

Q1: 27.5
Q3: 62.5
IQR: 35.0


In [45]:
# Q15. Use broadcasting to add a 1D array to every row of a 2D array

arr = np.arange(1,13).reshape(3,4)
print(arr)
arr1 = np.arange(1,5)
print(arr1)
result = arr + arr1
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
